### ISSUE TITLE
[FR] Make Client useable for any authenticated POST request

### ISSUE THREAD

**Issue by darthwalsh** [takos22/codingame#7]
**Is your feature request related to a problem? Please describe.**
I made a small [app](https://github.com/darthwalsh/DownloadCodinGame) that downloads all my CodinGame solutions. I need to make authenticated API requests to different URLs e.g. `https://www.codingame.com/services/Puzzle/findAllMinimalProgress`, `/Solution/findSolution`, etc.

I've now blocked with the login problem #5 and at the same time I was [guessing](https://www.codingame.com/playgrounds/53705/contest-tools-and-workflow/api-access-with-python#comment-5593119790) about some solution you were building it! (wow!)

**Describe the solution you'd like**
Add `codingame.Client.request(service: str, func: str, json: list = [])` to the [public API](https://codingame.readthedocs.io/en/stable/api.html#hybrid-client) for both the sync and async clients.

**Describe alternatives you've considered**
* I think my app could invoke `client.request()` but as it's undocumented it seems to be an internal API?
* I could add cookie session in my own repo, but I'd rather rely on some dedicated client to handle the logic.
* It would be awesome if this client natively supported the [various CodinGame APIs](https://sourcegraph.com/github.com/darthwalsh/DownloadCodinGame@main/-/blob/app.py?L53:10#tab=references) my puzzle solution download app needed, but that feels like a big request. Instead, having the generic `.request()` escape hatch enables the library to be used for any new APIs that CodinGame releases!

**Additional context**
I'm impressed by this project! Nice!

**Comment by takos22** [comment]
Currently the only way is to use the internal `HTTPClient` with `client._state.http.request(...)`, but I'll probably add `client.request` as an alias for it. I'm also planning on adding the endpoints that you use but that will take more time, because I want to finish the notifications first and then I'll work on puzzle related endpoints. 
Thanks for the ideas and feedback.

**Comment by takos22** [comment]
The next release (`1.2.0`) will implement [``Client.request`](https://codingame.readthedocs.io/en/1.2.x/api.html#codingame.Client.request) and it will probably come out today. Join [the discord server](https://discord.gg/8HgtN6E) if you want to be notified of the release.
